### PR TITLE
Add high level tests to PyLoopKit to mirror Loop

### PR DESCRIPTION
**Pull request by novalegra**
This PR adds the same high-level tests to PyLoopKit that are present in Loop (see https://github.com/tidepool-org/Loop/pull/200 for the associated Loop PR), which addresses https://github.com/tidepool-org/PyLoopKit/issues/16. To permit the fixture effects to be "injected" into the `update` function, I created a check for them in the input dictionary (which is actually similar to how I changed Loop to allow me to inject mock stores).

### CODE REVIEW

**Comment by novalegra** [comment]
@scaubrey Would it be possible to get a review by EOD tomorrow so I can wrap this up before I leave?

**Comment by scaubrey** [comment]
Wow, just found your comment @novalegra. Apologies. Maybe when you're back we can get this in. I am curious if this uses the `add-pulses` updates.

**Comment by novalegra** [comment]
> Wow, just found your comment @novalegra. Apologies. Maybe when you're back we can get this in. I am curious if this uses the `add-pulses` updates.

This doesn't incorporate the `add-pulses` updates, but happy to merge dev into this & resolve the conflicts!

**Comment by novalegra** [comment]
> > Wow, just found your comment @novalegra. Apologies. Maybe when you're back we can get this in. I am curious if this uses the `add-pulses` updates.
> 
> This doesn't incorporate the `add-pulses` updates, but happy to merge dev into this & resolve the conflicts!

I just merged everything in, and all tests are passing.

**Review by scaubrey — APPROVED** [review]
This looks good to me. Thanks for updating @novalegra!

**Pull request merged**
