### PR TITLE
fix: fixes counteraction_effects issue that occurs when no insulin data is passed in

### PR DESCRIPTION
**Pull request by edengh**
Fix counteraction_effects referenced before created error

### CODE REVIEW

**Comment by scaubrey** [comment]
@novalegra Does this seem like a reasonable fix? Does Loop handle this issue similarly?

**Comment by novalegra** [comment]
@scaubrey Yep, this is how Loop would do it.

**Comment by scaubrey** [comment]
Great, thanks @novalegra. Any idea why Loop doesn't every experience this error? Is it because this fix is in there or is it because Pyloopkit is somehow used differently?

**Comment by novalegra** [comment]
It's because Loop actually appends the result of the counteraction effects to those from the previous run, so it's building them up incrementally instead of running calculating all of the counteraction effects every time. The counteraction effects are initialized as an empty list. Because of PyLoopKit's usecase, it calculates all of the counteraction effects, but it seems like I forgot to have it return empty lists if the counteraction effects couldn't be calculated (which is what Loop would do)

**Comment by scaubrey** [comment]
Got it, thanks! Ok, so I'm going to say let's merge this then.

**Comment by scaubrey** [comment]
@novalegra Can you approve the PR and merge?

**Comment by scaubrey** [comment]
@edengh Just a reminder to request a review when you create the PR. I added Anna and me for review just now.

**Pull request merged**
